{"name": "test_negative_login_with_Wrong_User_Information_7_________________________", "status": "broken", "statusDetails": {"message": "TypeError: TestLoginFunctionality.test_negative_login_with_Wrong_User_Information() takes 3 positional arguments but 7 were given", "trace": "self = <tests.test_loginTest.TestLoginFunctionality testMethod=test_negative_login_with_Wrong_User_Information_7_________________________>\n\n    @wraps(func)\n    def wrapper(self):\n>       return func(self, *args, **kwargs)\nE       TypeError: TestLoginFunctionality.test_negative_login_with_Wrong_User_Information() takes 3 positional arguments but 7 were given\n\nvenv\\Lib\\site-packages\\ddt.py:220: TypeError"}, "start": 1677149215690, "stop": 1677149215691, "uuid": "801de20f-d865-4e84-90a4-d64fcd74a79e", "historyId": "9ad02c434667855cd2979e3e8aaeaccd", "testCaseId": "52530cf4095101d8848d80fe79c50fe2", "fullName": "tests.test_loginTest.TestLoginFunctionality#test_negative_login_with_Wrong_User_Information_7_________________________", "labels": [{"name": "tag", "value": "@pytest.mark.usefixtures('setup')"}, {"name": "parentSuite", "value": "tests"}, {"name": "suite", "value": "test_loginTest"}, {"name": "subSuite", "value": "TestLoginFunctionality"}, {"name": "host", "value": "DESKTOP-75D171T"}, {"name": "thread", "value": "13816-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.test_loginTest"}]}